name: Continuous Deployment

jobs:
	build:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v4

			- name: Setup CML
				uses: iterative/setup-cml@v2

			- name: Install Packages
				run: make install

			- name: Format Code
				run: make format

			- name: Train Model
				run: make train

			- name: Evaluate Model
				run: make eval

			- name: Upload Report
				uses: actions/upload-artifact@v4
				with:
					name: model-report
					path: report.md

			- name: Hugging Face Login
				env:
					HF_TOKEN: ${{ secrets.HF_TOKEN }}
				run: make hf-login

			- name: Deploy to Hugging Face
				run: make push-hub
